"""Add user_withdrawal table and cascade delete for user agreements

Revision ID: 07c568ffc274
Revises: 59acdbe1a2a5
Create Date: 2025-12-20 21:59:00.357533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '07c568ffc274'
down_revision: Union[str, None] = '59acdbe1a2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userwithdrawal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userwithdrawal_user_id'), 'userwithdrawal', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userwithdrawal_user_id'), table_name='userwithdrawal')
    op.drop_table('userwithdrawal')
    # ### end Alembic commands ###
