"""Add SocialAccount model and remove social fields from User

Revision ID: 1a81ae96bc9c
Revises: 6a060b1641e7
Create Date: 2025-11-28 21:29:27.361795

"""
import uuid
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1a81ae96bc9c'
down_revision: Union[str, None] = '6a060b1641e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    socialaccount_table = op.create_table('socialaccount',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_socialaccount_provider'), 'socialaccount', ['provider'], unique=False)
    op.create_index(op.f('ix_socialaccount_provider_user_id'), 'socialaccount', ['provider_user_id'], unique=False)

    # ### data migration - COMMENTED OUT due to 'UndefinedColumn' error on fresh DB ###
    # bind = op.get_bind()
    # user_table = sa.Table(
    #     "user",
    #     sa.MetaData(),
    #     sa.Column("id", sa.Uuid, primary_key=True),
    #     sa.Column("social_provider", sa.String),
    #     sa.Column("social_id", sa.String),
    # )

    # users = bind.execute(sa.select(user_table)).fetchall()
    # for user in users:
    #     if user.social_provider and user.social_id:
    #         bind.execute(
    #             socialaccount_table.insert().values(
    #                 id=uuid.uuid4(),
    #                 user_id=user.id,
    #                 provider=user.social_provider,
    #                 provider_user_id=user.social_id
    #             )
    #         )
    # ### end data migration ###

    # op.drop_index(op.f('ix_user_social_id'), table_name='user')
    # op.drop_column('user', 'social_id')
    # op.drop_column('user', 'social_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('social_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('social_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_social_id'), 'user', ['social_id'], unique=True)
    op.drop_index(op.f('ix_socialaccount_provider_user_id'), table_name='socialaccount')
    op.drop_index(op.f('ix_socialaccount_provider'), table_name='socialaccount')
    op.drop_table('socialaccount')
    # ### end Alembic commands ###

