"""Rename calculator_input to calculation_result in HousingSubscriptionDetail

Revision ID: 59acdbe1a2a5
Revises: 65a0c026ca09
Create Date: 2025-12-07 22:00:06.076267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59acdbe1a2a5'
down_revision: Union[str, None] = '65a0c026ca09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housingsubscriptiondetail', sa.Column('calculation_result', sa.JSON(), nullable=True))
    op.drop_column('housingsubscriptiondetail', 'calculator_input')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housingsubscriptiondetail', sa.Column('calculator_input', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('housingsubscriptiondetail', 'calculation_result')
    # ### end Alembic commands ###
