"""dummy_fix

Revision ID: 6a060b1641e7
Revises: ccd26c6c5dd5
Create Date: 2024-01-01 00:00:00.000000

"""


# revision identifiers, used by Alembic.
revision = '6a060b1641e7'
down_revision = 'ccd26c6c5dd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
