"""add terms and useragreement tables

Revision ID: 6de4152aa952
Revises: 1a81ae96bc9c
Create Date: 2025-12-02 21:55:11.816778

"""
import datetime
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6de4152aa952'
down_revision: Union[str, None] = '1a81ae96bc9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    terms_table = op.create_table('terms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('term_type', sa.Enum('TERMS_OF_USE', 'PRIVACY_POLICY', name='termtype'), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_created_at'), 'terms', ['created_at'], unique=False)
    op.create_index(op.f('ix_terms_term_type'), 'terms', ['term_type'], unique=False)
    op.create_table('useragreement',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('terms_id', sa.Uuid(), nullable=False),
    sa.Column('agreed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['terms_id'], ['terms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'terms_id')
    )
    # ### end Alembic commands ###

    # Re-define terms_table explicitly for bulk_insert to include all columns
    terms_table = sa.Table(
        'terms',
        sa.MetaData(),
        sa.Column('id', sa.Uuid(), primary_key=True),
        sa.Column('term_type', sa.Enum('TERMS_OF_USE', 'PRIVACY_POLICY', name='termtype')),
        sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50)),
        sa.Column('content', sqlmodel.sql.sqltypes.AutoString()),
        sa.Column('created_at', sa.DateTime()),
    )
    op.bulk_insert(
        terms_table,
        [
            {
                "id": uuid.uuid4(),
                "term_type": "TERMS_OF_USE",
                "version": "1.0",
                "content": "서비스 이용약관 내용입니다.",
                "created_at": datetime.datetime.utcnow(),
            },
            {
                "id": uuid.uuid4(),
                "term_type": "PRIVACY_POLICY",
                "version": "1.0",
                "content": "개인정보 처리방침 내용입니다.",
                "created_at": datetime.datetime.utcnow(),
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useragreement')
    op.drop_index(op.f('ix_terms_term_type'), table_name='terms')
    op.drop_index(op.f('ix_terms_created_at'), table_name='terms')
    op.drop_table('terms')
    op.execute("DROP TYPE termtype")
    # ### end Alembic commands ###
