"""Alter UserWithdrawal withdrawn_at to support timezone

Revision ID: e8763be0e4bb
Revises: ec0cc10ab699
Create Date: 2025-12-21 22:10:15.224133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8763be0e4bb'
down_revision: Union[str, None] = 'ec0cc10ab699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('item_owner_id_fkey'), 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'user', ['owner_id'], ['id'])
    op.drop_constraint(op.f('socialaccount_user_id_fkey'), 'socialaccount', type_='foreignkey')
    op.create_foreign_key(None, 'socialaccount', 'user', ['user_id'], ['id'])
    op.alter_column('userwithdrawal', 'withdrawn_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userwithdrawal', 'withdrawn_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'socialaccount', type_='foreignkey')
    op.create_foreign_key(op.f('socialaccount_user_id_fkey'), 'socialaccount', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key(op.f('item_owner_id_fkey'), 'item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
