"""Rename email to hashed_email and update type in UserWithdrawal

Revision ID: ec0cc10ab699
Revises: 07c568ffc274
Create Date: 2025-12-21 17:57:20.679461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec0cc10ab699'
down_revision: Union[str, None] = '07c568ffc274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userwithdrawal', sa.Column('hashed_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_userwithdrawal_hashed_email'), 'userwithdrawal', ['hashed_email'], unique=False)
    op.drop_column('userwithdrawal', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userwithdrawal', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_userwithdrawal_hashed_email'), table_name='userwithdrawal')
    op.drop_column('userwithdrawal', 'hashed_email')
    # ### end Alembic commands ###
